### ISSUE TITLE
how

### ISSUE THREAD

**Issue by nikeedev** [xNoobplays123/conspiracy-theories#2]
![image](https://user-images.githubusercontent.com/69197950/198703156-40240f76-fae6-4b28-b653-e37450bb639d.png)

**Comment by nikeedev** [comment]
tell me

**Comment by nikeedev** [comment]
no

**Comment by nikeedev** [comment]
how? =)
@xNoobplays123?


@nikeedev
![nikee_big](https://user-images.githubusercontent.com/69197950/198703454-f9e363ce-24b1-49d3-ab39-9475d6a19d22.png)

**Comment by xNoobplays123** [comment]
Why you spamming, I get a email every time a new issue is opened

**Comment by nikeedev** [comment]
its fun
